### PR TITLE
GIT Workshop Assignment

### PR DESCRIPTION
**Pull request by aditikharel**
Added my story following all instructions.

### CODE REVIEW

**Review by ABoredComputerEngineer — CHANGES_REQUESTED** [review]
Please change the filename to your **Github username**.

**Comment by aditikharel** [comment]
> Please change the filename to your **Github username**.

I changed my github username, if that's okay XD

**Comment by aditikharel** [comment]
> Please change the filename to your **Github username**.

The changes have been made.

**Comment by rabinadk1** [comment]
LGTM!

**Pull request merged**
