### PR TITLE
GIT-Workshop Assignment

### PR DESCRIPTION
**Pull request by Mamata-Maharjan**
Assignment of GIT WORKSHOP , LOCUS 2021.
077BCT043- Mamata Maharjan

### CODE REVIEW

**Review by rabinadk1 — CHANGES_REQUESTED** [review]
Move your file inside the `Stories` folder to maintain repository consistency.

**Comment by rabinadk1** [comment]
You needn't close this pull request to reflect the changes.

**Comment by Mamata-Maharjan** [comment]
I was very much confused. I couldn't find out how to send the file in
stories folder. I tried putting the file in stories folder (that was saved
in file explorer) but couldn't actually see the changes in git website.
So I redid it all, putting files in the stories folder from the
very beginning.(got more understanding doing it the second time)
 I am still confused if i did it correctly this time..
Please let me know, and give me directions if i have done it incorrectly
the second time as well.
(Mamata-Maharjan)

**Comment by rabinadk1** [comment]
> I was very much confused. I couldn't find out how to send the file in stories folder. I tried putting the file in stories folder (that was saved in file explorer) but couldn't actually see the changes in git website. So I redid it all, putting files in the stories folder from the very beginning.(got more understanding doing it the second time) I am still confused if i did it correctly this time.. Please let me know, and give me directions if i have done it incorrectly the second time as well. (Mamata-Maharjan)

Seems like you have figured it out. Your another pull request, #25  is accepted. Happy Coding!!

**Comment by Mamata-Maharjan** [comment]
> > I was very much confused. I couldn't find out how to send the file in stories folder. I tried putting the file in stories folder (that was saved in file explorer) but couldn't actually see the changes in git website. So I redid it all, putting files in the stories folder from the very beginning.(got more understanding doing it the second time) I am still confused if i did it correctly this time.. Please let me know, and give me directions if i have done it incorrectly the second time as well. (Mamata-Maharjan)
> 
> Seems like you have figured it out. Your another pull request, #25 is accepted. Happy Coding!!

Thankyou very much ... 
Thankyou very much for the the Git-Workshop.

**Pull request closed without merging**
