### PR TITLE
Branch third

### PR DESCRIPTION
**Pull request by av0t**
This is the assignment for the Git-workshop.

### CODE REVIEW

**Review by ABoredComputerEngineer — CHANGES_REQUESTED** [review]
Sorry, but your commit history does not show any merge conflicts being resolved. Please review it once! (Your PR will still be accepted once you make the changes )

**Review by av0t — COMMENTED** [review]
changes made.

**Comment by av0t** [comment]
changes made, please review it again.

**Comment by ABoredComputerEngineer** [comment]
Your assignment is complete. Thank you for your submission!

**Pull request merged**
