### PR TITLE
Assignment (Rujal Acharya)

### PR DESCRIPTION
**Pull request by RujalAcharya**
This is my submission for the completion of assignment.
I feel like I have fulfilled all the required conditions..
Do let me know if there is any problem or mistake...
also, do check the story

### CODE REVIEW

**Comment by ABoredComputerEngineer** [comment]
Please add your email as well on the story file.

**Review by ABoredComputerEngineer — CHANGES_REQUESTED** [review]
Please add your email as well!

**Comment by RujalAcharya** [comment]
I have made the requested changes..

**Comment by ABoredComputerEngineer** [comment]
Thank you for your submission!

**Pull request merged**
