### PR TITLE
Assignment submitted

### PR DESCRIPTION
**Pull request by Rabin002**
I completed my assignment as per the instructions given.

### CODE REVIEW

**Review by rabinadk1 — CHANGES_REQUESTED** [review]
Rename your file to your GitHub username i.e. `Rabin002.txt` for repository consistency and uniqueness.

**Review by Rabin002 — COMMENTED** [review]
File renamed.

**Review by rabinadk1 — CHANGES_REQUESTED** [review]
Delete `Rabin.txt`

**Review by Rabin002 — COMMENTED** [review]
Rabin.txt deleted.

**Comment by rabinadk1** [comment]
LGTM! Happy Coding :)

**Pull request merged**
