### PR TITLE
Workshop assignment

### PR DESCRIPTION
**Pull request by optimistic-ish**
Hope I have done everything I was supposed to. Thank you for the awesome workshop.

### CODE REVIEW

**Review by ABoredComputerEngineer — CHANGES_REQUESTED** [review]
Please change the filename to your **github username**.

**Comment by optimistic-ish** [comment]
I have changed it.

**Review by ABoredComputerEngineer — CHANGES_REQUESTED** [review]
You have added 2 files. Please include only `optimistic-ish.txt`.

**Comment by optimistic-ish** [comment]
I think  it should be fixed now.

**Comment by ABoredComputerEngineer** [comment]
Thank you for your submission!

**Pull request merged**
